# Site settings
title:          
description:    "Rain is a simple and clean Jekyll theme with focus on content."
url:            https://github.com/inelaah/rain

# Author
author:
  name:         Péter Garamvölgyi
  email:        peter.garamvolgyi@hotmail.com
  url:          --

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji # Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       100

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  # email: inelaah@gmail.com
  github: https://github.com/Thegaram
  twitter: https://twitter.com/thegaram33
  # linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
